/**
 * An id generator to be used for each Todo
 * In a 'real-world' version of the app, ids would be generated by the database
 * 
 * @returns Randomly generated integer
 */
export const generateRandomId: () => number = () => parseInt(Math.random().toString().substr(2));
